{% set name = "py-tes" %}
{% set version = "0.4.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: f6926cd59b7dfc8e37840955bf1cc7c43ad4d99ba5eae100b6156c918617472c

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - attrs >=17.4.0
    - future >=0.16.0
    - pip
    - python {{ python_min }}
    - python-dateutil >=2.6.1
    - requests >=2.18.2
  run:
    - attrs >=17.4.0
    - future >=0.16.0
    - python >={{ python_min }}
    - python-dateutil >=2.6.1
    - requests >=2.18.2

test:
  requires:
    - python {{ python_min }}
  imports:
    - tes

about:
  home: "https://github.com/ohsu-comp-bio/py-tes"
  license: MIT
  license_family: MIT
  license_file: '{{ RECIPE_DIR }}/LICENSE'
  summary: "Library for communicating with the GA4GH Task Execution API"
  dev_url: https://github.com/ohsu-comp-bio/py-tes

extra:
  recipe-maintainers:
    - johanneskoester
